#
# CSE186 Assignment 7 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 7 Backend
  version: 0.2.0
  title: CSE186 Assignment 7 Backend

servers:
  - url: http://localhost:3010/api/v0

paths:
  /mail:
    get: # Should have content property removed
      summary: Return all Mail, Content Removed
      parameters:
        - name: mailbox
          in: query
          required: false
          schema:
            type: string
            example: "inbox"
      responses:
        200:
          description: List of Mail
          content:
            application/json:
              schema: # Reuse Email Schema
                type: array
                items:
                  $ref: '#/components/schemas/Mailbox'
        404:
          description: Not Found
 
  /mailbox:
    get:
      summary: Return Mailbox Names
      responses:
        200:
          description: List of Mailbox Names
          content:
            application/json:
              schema: # Reuse MailboxName Schema
                type: array
                items:
                  $ref: '#/components/schemas/MailboxName'
        404:
          description: Not Found

  # WIP
  /mail/{id}:
    put:
      summary: Move Email into Named Mailbox
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: "746c5739-ad9d-4052-8123-af6b33dd61a6"    
        - name: mailbox
          in: query
          required: true
          schema:
            type: string
            example: "inbox"
      responses:
        204:
          description: Email Successfully moved
        404:
          description: Email not found


components:
  schemas:
    Mailbox:
      type: object
      properties:
        name:
          type: string
          example: inbox
        mail:
          type: array
          items:
            $ref: '#/components/schemas/Email'
      required: 
        - name
        - mail

    MailboxName:
        type: string
        example: "inbox"

    newEmail:
      type: object
      description: Client Input
      additionalProperties: false
      properties:
        to:
          type: object
          additionalProperties: false
          properties:
            name:
              type: string
              example: "Bill Murray"
            email:
              type: string
              example: "garfield@ucsc.edu"
          required:
            - name
            - email
        subject:
          type: string
          example: "Broderskab (Brotherhood)"
        content:
          type: string
          example: "Duis aliquam convallis nunc."
      required:
        - to
        - subject
        - content

    Email:
      type: object
      description: Email Data - No Content
      properties:
        id:
          type: string 
          format: uuid
          example: "591b428e-1b99-4a56-b653-dab17210b3b7"
        from:
          type: object
          properties:
            name:
              type: string
              example: "John Pork"
            email:
              type: string
              example: "johnpork@gmail.com"
          required:
            - name
            - email
        to:
          type: object
          properties:
            name:
              type: string
              example: "CSE-Student"
            email:
              type: string
              example: "csestudent@gmail.com"
          required:
            - name
            - email
        subject:
          type: string
          example: "Broderskab (Brotherhood)"
        sent: 
          type: string 
          format: date-time
          example: "2020-07-07T00:18:37Z"
        received:
          type: string 
          format: date-time
          example: "2020-07-07T00:18:37Z"
      required:
        - id
        - from
        - to
        - subject
        - sent
        - received

    EmailandContent:
      description: Email Date + Content
      allOf: # Allows extra properties to be added
        - $ref: '#/components/schemas/Email'
        - type: object
          properties:
            content:
              type: string
              example: "Duis aliquam convallis nunc."
          required: 
            - content