#
# CSE186 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 8 Backend
  version: 4.1.0
  title: CSE186 Assignment 8 Backend

servers:
  - url: http://localhost:3010/api/v0

paths:
  /login:
    post:
      summary: Grab Login Info and Verify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
              
      responses:
        200:
          description: Login Succesful, Return JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string

components:
  schemas:
    Credentials:
      type: object
      properties:
        email:
          type: string
          example: "molly@books.com"
        password:
          type: string
          format: password
          example: "mollymember"
      required:
        - email
        - password

    User:
      type: object
      required:
        - user
        - accessToken
      properties:
        user:
          type: object
          required:
            - id
            - email
          properties:
            id:
              type: string
            name:
              type: string
            email:
              type: string
        accessToken:
          type: string

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes