#
# CSE186 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 8 Backend
  version: 4.1.0
  title: CSE186 Assignment 8 Backend

servers:
  - url: http://localhost:3010/api/v0

paths:
  /login:
    post:
      summary: Grab Login Info and Verify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
              
      responses:
        200:
          description: Login Succesful, Return JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string

  /userPost:
    get:
      summary: Grab All Posts
      security:
        - bearerAuth: []
      responses:
        200:
          description: Authenticated, Show Posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posts'
        401:
          description: Unauthorized Access


                
components:
  schemas:
    Credentials:
      type: object
      properties:
        email:
          type: string
          example: "molly@books.com"
        password:
          type: string
          format: password
          example: "mollymember"
      required:
        - email
        - password

    User:
      type: object
      required:
        - user
        - accessToken
      properties:
        user:
          type: object
          required:
            - id
            - email
          properties:
            id:
              type: string
            name:
              type: string
            email:
              type: string
        accessToken:
          type: string

    Post:
      description: Singular Post
      type: object
      required:
        - id
        - username
        - content
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        content:
          type: string


    Posts:
      description: List of Posts
      type: object
      required:
        - posts
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'

# {
#   "posts": [
#     {
#       "id": "uuid",
#       "username": "Aye Astro",
#       "content": "Hello world!"
#     }
#   ]
# }

# {
#   "posts": [
#     {
#       "id": "3f4c6e4b-7a65-4a1e-8d2c-5f6dce9f2a2a",
#       "username": "Aye Astro",
#       "content": "Hello world!"
#     },
#     {
#       "id": "8a9c4c4f-21f0-4c0c-9c16-92a52c4c8f21",
#       "username": "Molly Maze",
#       "content": "Hey everyone!"
#     }
#   ]
# }

    securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT    # optional, arbitrary value for documentation purposes